### ISSUE TITLE
仿真中无法控制EP的机械爪

### ISSUE THREAD

**Issue by LebinLiang** [AIR-DISCOVER/ICRA2024-Sim2Real-RM#1]
根据教程进行部署后，启动了键盘遥控节点，可以正常控制机械臂升降，但是无法控制机械爪的开合，发布arm_gripper话题也无法控制。

**Comment by Tongdakang** [comment]
请问，你最后如何解决这个问题呢？

**Comment by LebinLiang** [comment]
他所没有夹取动画，就对准了就可以抓取
